### ISSUE TITLE
Investigate relenvs v3 keystore issue

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1452]
The IG keystore is not being loaded correctly in relenvs v3.

The issue is affecting both Core and OB deployments.

Start by investigating the Core deployment, the issue can be reproduced by calling the this endpoint: `https://sapig.core-sandbox-v3.forgerock.financial/jwkms/apiclient/issuecert`

The endpoint will be loading the Test Trusted Directory CA keystore.

It is likely that the keystore secret has been corrupted (or is in the wrong format).

**Comment by dbadham-fr** [comment]
The keystore does not appear to be in PKC12 format (as it is required to be).

To test this, you can retrieve the keystore as a binary secret and attempt to open it using keytool:
```
keytool -list -keystore test.jks -storetype PKCS12
```
This returns the following error:
```
keytool error: java.io.IOException: toDerInputStream rejects tag type 51
```

**Comment by shaunharrisonFR** [comment]
Investigating!

**Comment by shaunharrisonFR** [comment]
Can you retry `core` when you are online please @dbadham-fr 

So this is the first time we've created a separate secret instead of using the existing `test-trusted-dir-keystore` secret. As you mentioned the secret was not in the correct format, updated both `v3-ob-test-trusted-dir-keystore` and `v3-core-test-trusted-dir-keystore`

Think OB still may have config missing as IG is not starting up

**Comment by shaunharrisonFR** [comment]
Comment above was half the problem

The issue with OB was that the ig-ob-signing-key secret key was named `ig-corfe-signing-key.p12` and not the expected `ig-ob-signing-key.p12`

Created a helpers 3.0.1 and deployed to relenv which has now let IG start up
