### ISSUE TITLE
Support making ig-truststore-pem secret optional for core deployment

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1507]
A deployment may not need to specify any additional certs to add to their IG truststore.

We would like to allow the `ig-truststore-pem` to be optional.

The initContainer for the IG deployment still needs to be run in order to produce the IG truststore which is referenced in the config.json. Therefore, the [import-pem-certs.sh](https://github.com/SecureApiGateway/secure-api-gateway-core/blob/main/secure-api-gateway-core-docker/7.3.0/ig/bin/import-pem-certs.sh) script needs to be tweaked to only copy the default trusted certs (from the JDK cacerts file) into the new truststore if no addtional certs are supplied.

**Comment by dbadham-fr** [comment]
I think a better approach is to tweak the script executed by the init container so that it does not fail if there are no secrets. The init container will run but do nothing.

Then we can make the ig-truststore-pem secret optional, and retain the initcontainer.

If a customer wishes to add certs to the truststore then they simply need to provide the secret.

With this approach we can have a single deployment.yaml
