### ISSUE TITLE
sbat-infra destroy pipeline failing - Error waiting for Deleting Network

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#489]
Destroy pipeline is failing with the following error:
```
Error: Error waiting for Deleting Network: The network resource 'projects/sbat-dev/global/networks/sbat-master' is already being used by 'projects/sbat-dev/zon
es/europe-west4-a/networkEndpointGroups/k8s1-e5924963-bohocode-cdk-end-user-ui-8080-054b2e21'      
```

Example build failure: https://g.codefresh.io/build/62fe4cc145c2622bfc4c31c0?step=destroy_infrastructure&tab=output&logs=terminal

Failure to delete network resources means that we accumulate objects in GKE which are no longer used, it can also cause failures in the start of day create pipeline, example failure: https://g.codefresh.io/build/62f49630ba38df84dfec4ab0?step=apply_infrastructure&tab=output&logs=terminal

The issue is related to the following known issue with GKE & terraform: https://github.com/hashicorp/terraform-provider-google/issues/7637

> This is a known issue. GKE creates resources that use the network/subnetwork out of band(outside of terraform).
> When you delete the GKE Cluster, the resources it created such as IPs/NEGs/LBs are deleted but it may not be deleted immediately so when terraform is destroying the subnets it will fail as the NEG might still be around.
> You can ensure this doesn’t happen by deleting the Ingresses/Services before you destroy the cluster

From the above issue it sounds like the solution is to manually delete our k8s resources before calling the terraform destroy. We will need to create a script to do this and add a step in our destroy pipeline.

Shaun Edit - Google Issue Tracker - https://issuetracker.google.com/issues/186792016?pli=1

**Comment by shaunharrisonFR** [comment]
@BohoCode happy to pick up the suggestion of removing the K8s resources manually - Once I have GCP access it'll be a good ticket for me to see the ins and outs of our infra

**Comment by shaunharrisonFR** [comment]
Bit of a work around for the time being, the pipeline will now run a script which will remove the network security groups that are set to 0 (not in use) and for the zone we are using

This however doesn't destroy the active ones, which are still in use, so terraform destroy will run and then the two commands are reran for the ones that are newly set to 0 after the first terraform destroy will then get cleaned up, so that ultimately the VPC and be destoryed

There will be a new ticket in future to clean this up a bit as there is a bit of forced push through via exit 0
