### ISSUE TITLE
Estimate and plan 'Ensure that all API validations are implemented'

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#567]
See description in #391 

Decide where validation should be implemented, and how we can provide validation for customers implementing there own RS.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/567?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris

**Comment by dbadham-fr** [comment]
Basic validation that a consent adheres to the OBIE Read/Write swagger spec will be handled for free by the RS when we move consent processing to it, Spring will handle validation of the API types.

There are additional validations which aren't captured by the swagger spec which must be implemented by all ASPSPs, examples:

- Payment Request's Initiation and Risk fields must match those in the Consent
- **TBC further investigation needed**

**Comment by dbadham-fr** [comment]
Turns out that we are currently not using the enforcing the javax.validation annotations on the generated OBIE datamodel code. I believe we are doing this in the OBRI SaaS product.

I'm going to investigate turning it on in the SBAT RS.
In addition to enabling this functionality, we will need a strategy for catching validation errors that are raised and converting them into a valid OB API response.

**Comment by dbadham-fr** [comment]
I have updated the description in the epic and have raised individual issues under the epic which form the high level pieces of work required. Estimates are rough at this point and should be revisited when we come to schedule the work.
