### ISSUE TITLE
Complete Dynamic Client Registration endpoints; GET, PUT and DELETE paths

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#597]
Currently the DCR endpoint only supports the POST, and to a small degree the DELETE HTTP methods. I needs to comply with the DCR 3.2 spec.

**Comment by dbadham-fr** [comment]
The GET/PUT/DELETE requests are all broken due to the differences in the URI format between the OBIE spec and AM.

AM expects the client_id to be supplied as a url param, whereas OBIE specifies it as the last element in the path. https://backstage.forgerock.com/docs/am/7.2/oidc1-guide/oauth2-dynamic-client-registration.html

A further issue is that for POST (creating a new OAuth client), there are no access tokens supplied by the TPP, therefore, for security, we enforce that IG must present OAuth credentials. This breaks the GET/PUT/DELETE flows, as they need to use the `registration_access_token` from the DCR response rather than IG credentials.

The solution to this is to have 2 routes in IG for DCR, one which is used for POST (creating a new DCR), and one for GET/PUT/DELETE (modifying an existing DCR).

**Comment by dbadham-fr** [comment]
TO DO: Review whether it makes sense to have 2 routes for DCR (see above), we may be able to make use of a SwitchFilter instead to add the IG access token as needed when doing a POST
